language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
# command to run tests
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - pytest tests/test_nqueens.py
